#!/usr/bin/env node

var width = 960,
    height = 500,
    projectionName = process.argv[2],
    projectionSymbol = "geo" + projectionName[0].toUpperCase() + projectionName.slice(1),
    rotate, angle, translate;

if (!/^[a-z0-9]+$/i.test(projectionName)) throw new Error;

var fs = require("fs"),
    topojson = require("topojson-client"),
    Canvas = require("canvas"),
    d3 = Object.assign({}, require("d3-geo"), require("../"));

var canvas = new Canvas(width, height),
    context = canvas.getContext("2d");

var world = require("world-atlas/world/50m.json"),
    land = topojson.feature(world, world.objects.land),
    graticule = d3.geoGraticule(),
    outline = {type: "Sphere"};

switch (projectionName) {
  case "littrow": outline = graticule.extent([[-90, -60], [90, 60]]).outline(); break;
  case "modifiedStereographicGs50": outline = graticule.extent([[-180, 15], [-50, 75]]).outline(); break;
  case "modifiedStereographicMiller": outline = graticule.extent([[-40, -40], [80, 80]]).outline(); break;
  case "tetrahedralLeeSouth": projectionSymbol = "geoTetrahedralLee"; rotate = [-30,0]; angle = -30; translate = [599.204, 98.0632]; break;
  // Outline cannot be rendered properly using complex log
  case "complexLog": outline = {type: "Point", coordinates: []}; break;
}

var projection = d3[projectionSymbol]().precision(0.1),
    path = d3.geoPath()
      .projection(projection)
      .context(context);

if (rotate) projection.rotate(rotate);
if (translate) projection.translate(translate);
if (angle) projection.angle(angle);

context.fillStyle = "#fff";
context.fillRect(0, 0, width, height);

context.beginPath();
path(land);
context.fillStyle = "#000";
context.fill();

context.beginPath();
path(graticule());
context.strokeStyle = "rgba(119,119,119,0.5)";
context.stroke();

context.beginPath();
path(outline);
context.strokeStyle = "#000";
context.stroke();

canvas.pngStream().pipe(process.stdout);
